<h1>Cadastro de Usuários</h1>

<form method="post" action="Request.php?class=UserCtr&method=run">
            <!-- input para o id (oculto) do objeto  -->
            <input type="hidden" name="id" id="id" 
                   value="<?= $this->model->getId() ?>">

            <label for="name">Nome:</label>
            <input type="text" name="name" id="name" required maxlength="50"
                   value="<?= $this->model->getName() ?>">
            <br>


            <label for="gender">Sexo:</label>
            <select name="gender" id="gender">
                <option value="M" <?= $this->model->getGender() == 'M' ? 'selected' : '' ?>
                        >Masculino</option>
                <option value="F" <?= $this->model->getGender() == 'F' ? 'selected' : '' ?> 
                        >Feminino</option>
            </select>
            <br>
            
            <label for="email">E-mail:</label>
            <input type="email" name="email" id="email" required maxlength="50"
                   value="<?= $this->model->getEmail() ?>">
                   <img id="loader" src="" style="width:32px;">
            <br>
            <fieldset>
            <legend>Cidade:</legend>
                <label for="city">Id:</label>
                <input type="number" name="city" id="city" step="1" value="<?=$this->model->getCity()->getId()?>">
                <label for="namecity">Nome:</label>
                <input type="text" name="namecity" id="namecity" readonly value="<?=$this->model->getCity()->getName() . "/" . $this->model->getCity()->getState() ?>">
                <button id="btncity" name="btncity">Pesquisar</button>
            </fieldset>

            <label>Senha:
                <input type="password" id="password" required name="password" >                
            </label>
            <br>
            <button type="submit" name="command" value="Novo">
                Novo
            </button>

            <button type="submit" name="command" value="Salvar">
                Salvar
            </button>

            <button type="submit" name="command" value="Salvar">
                Excluir
            </button>

            </form>


<!-- adiciona a Jquery -->
<script src='core/vendor/js/jquery-3.3.1.min.js'></script>

<!-- scripts ajaxa da página -->
<script>
    //ao sair do input cujo id é idcity
    $("#city").blur(function () {
        if($("#city").val() != ''){ //..se o elemento do form cujo id é idcity não estiver vazio, então...
        //..cria a url para a requisição - observe a variável fornecida via get
        url = "http://localhost/SysMoney/Request.php?class=CityCtr&method=getCity&idcity=" + $("#city").val();
        $.getJSON(url, function (data) { //..usa a função getJSON do jquery
                if(data != null){
                    //..se retornou cidade, então seta os valores no form
                    $("#namecity").val(data['name_city'] + '/' + data['state_city']);                    
                } else{ //..senão, limpa o idcity, seta o foco nele e exibe um alerta
                    $("#city").val('');
                    $("#city").focus();
                    alert('Cidade não encontrada!');                    
                }
            }
        );
        }
    });


    //..verificar se o e-mail já está cadastrado no banco de dados. 
    $("#email").blur(function () {
        $("#loader").attr('src','');
        if($("#email").val() != ''){
            $("#loader").attr('src','core/img/loading.gif');
            url = "http://localhost/SysMoney/Request.php?class=UserCtr&method=emailExists&email=" + $("#email").val(); 
            $.getJSON(url,function (data) {
                if(data == false)    
                    $("#loader").attr('src','core/img/checked.png');    
                else{
                    $("#loader").attr('src','core/img/warning.png');
                    $("#email").focus();
                }
            }
            );            
        }
    });


</script>
